import 'dart:collection';

/// LRU set of recent `eventId`s — used to prevent the same backend event
/// from being processed twice when it arrives over both SignalR and FCM.
///
/// We dedupe on the EXTERNAL eventId (UUID generated by the backend),
/// not on a local timestamp, so the order of arrival doesn't matter.
///
/// Capacity is intentionally tiny (100). Realtime pushes are not bursty
/// enough to need anything bigger, and the memory footprint stays trivial.
class EventDedupCache {
  EventDedupCache._();
  static final EventDedupCache instance = EventDedupCache._();

  static const int _capacity = 100;
  final LinkedHashSet<String> _seen = LinkedHashSet<String>();

  /// Returns `true` if [eventId] has already been seen. Always marks it as
  /// seen for the next call (LRU bump).
  ///
  /// `null` or empty `eventId`s are NEVER considered duplicates — we can't
  /// dedupe them, so we let them through.
  bool contains(String? eventId) {
    if (eventId == null || eventId.isEmpty) return false;
    return _seen.contains(eventId);
  }

  bool isDuplicate(String? eventId) {
    if (eventId == null || eventId.isEmpty) return false;
    final hit = _seen.remove(eventId);
    _seen.add(eventId);
    while (_seen.length > _capacity) {
      _seen.remove(_seen.first);
    }
    return hit;
  }

  /// Marks [eventId] as seen without checking. Useful for the producer side
  /// (e.g. SignalR handler) to register an event before FCM mirror arrives.
  void mark(String? eventId) {
    if (eventId == null || eventId.isEmpty) return;
    _seen.remove(eventId);
    _seen.add(eventId);
    while (_seen.length > _capacity) {
      _seen.remove(_seen.first);
    }
  }

  void clear() => _seen.clear();
  int get size => _seen.length;
}
